CREATE TABLE `provider_profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`providerRole` enum('counselor','case_manager','ecm_worker','probation_officer','insurance_provider','housing_provider','employment_specialist','peer_support_specialist','medical_provider','admin') NOT NULL,
	`organizationName` varchar(255) NOT NULL,
	`organizationType` varchar(100),
	`licenseNumber` varchar(100),
	`licenseType` varchar(100),
	`licenseState` varchar(50),
	`licenseExpiration` varchar(20),
	`yearsOfExperience` int,
	`certifications` text,
	`servicesProvided` text,
	`specializations` text,
	`targetPopulations` text,
	`primaryClientOutcome` text,
	`secondaryOutcomes` text,
	`measurableMetrics` text,
	`maxClientsPerMonth` int,
	`averageClientsServed` int,
	`acceptingNewClients` boolean DEFAULT true,
	`serviceDeliveryMethod` varchar(100),
	`collaboratingAgencies` text,
	`dataSharing` boolean DEFAULT false,
	`consentRequired` boolean DEFAULT true,
	`phone` varchar(20),
	`email` varchar(320),
	`onboardingComplete` boolean DEFAULT false,
	`onboardingStep` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `provider_profiles_id` PRIMARY KEY(`id`),
	CONSTRAINT `provider_profiles_userId_unique` UNIQUE(`userId`)
);
